# Code generated by Claude. Please open up an issue at https://github.com/nekorubu/flavor-text/issues if something goes wrong.
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
